# Generated by Django 4.0.2 on 2022-05-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='sqm',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
    ]
